<?php

namespace Database\Seeders;

use App\Enums\TypeTechnology;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class TechnologySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('technologies')->insert([
            [
                'name' => 'alpinejs',
                'slug' => Str::slug('alpinejs'),
                'type' => TypeTechnology::type_frontend,
                'icon' => '/assets/icons/alpinejs/alpinejs-original.svg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'amazonwebservices',
                'slug' => Str::slug('amazonwebservices'),
                'type' => TypeTechnology::type_cloud,
                'icon' => '/assets/icons/amazonwebservices/amazonwebservices-original-wordmark.svg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'apache',
                'slug' => Str::slug('apache'),
                'type' => TypeTechnology::type_backend,
                'icon' => '/assets/icons/apache/apache-original.svg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'axios',
                'slug' => Str::slug('axios'),
                'type' => TypeTechnology::type_frontend,
                'icon' => '/assets/icons/axios/axios-plain.svg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'azuredevops',
                'slug' => Str::slug('azuredevops'),
                'type' => TypeTechnology::type_cloud,
                'icon' => '/assets/icons/azuredevops/azuredevops-original.svg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'bash',
                'slug' => Str::slug('bash'),
                'type' => TypeTechnology::type_devops,
                'icon' => '/assets/icons/bash/bash-original.svg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'bootstrap',
                'slug' => Str::slug('bootstrap'),
                'type' => TypeTechnology::type_frontend,
                'icon' => '/assets/icons/bootstrap/bootstrap-original.svg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'cloudflare',
                'slug' => Str::slug('cloudflare'),
                'type' => TypeTechnology::type_cloud,
                'icon' => '/assets/icons/cloudflare/cloudflare-original.svg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'composer',
                'slug' => Str::slug('composer'),
                'type' => TypeTechnology::type_backend,
                'icon' => '/assets/icons/composer/composer-original.svg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'csharp',
                'slug' => Str::slug('csharp'),
                'type' => TypeTechnology::type_backend,
                'icon' => '/assets/icons/csharp/csharp-original.svg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'css3',
                'slug' => Str::slug('css3'),
                'type' => TypeTechnology::type_frontend,
                'icon' => '/assets/icons/css3/css3-original.svg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'digitalocean',
                'slug' => Str::slug('digitalocean'),
                'type' => TypeTechnology::type_cloud,
                'icon' => '/assets/icons/digitalocean/digitalocean-original.svg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'docker',
                'slug' => Str::slug('docker'),
                'type' => TypeTechnology::type_devops,
                'icon' => '/assets/icons/docker/docker-original.svg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'git',
                'slug' => Str::slug('git'),
                'type' => TypeTechnology::type_devops,
                'icon' => '/assets/icons/git/git-original.svg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'github',
                'slug' => Str::slug('github'),
                'type' => TypeTechnology::type_devops,
                'icon' => '/assets/icons/github/github-original-negative.svg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'html5',
                'slug' => Str::slug('html5'),
                'type' => TypeTechnology::type_frontend,
                'icon' => '/assets/icons/html5/html5-original.svg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'java',
                'slug' => Str::slug('java'),
                'type' => TypeTechnology::type_backend,
                'icon' => '/assets/icons/java/java-original.svg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'javascript',
                'slug' => Str::slug('javascript'),
                'type' => TypeTechnology::type_frontend,
                'icon' => '/assets/icons/javascript/javascript-original.svg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'jquery',
                'slug' => Str::slug('jquery'),
                'type' => TypeTechnology::type_frontend,
                'icon' => '/assets/icons/jquery/jquery-original.svg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'json',
                'slug' => Str::slug('json'),
                'type' => TypeTechnology::type_data,
                'icon' => '/assets/icons/json/json-original.svg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'laravel',
                'slug' => Str::slug('laravel'),
                'type' => TypeTechnology::type_backend,
                'icon' => '/assets/icons/laravel/laravel-original.svg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'linux',
                'slug' => Str::slug('linux'),
                'type' => TypeTechnology::type_devops,
                'icon' => '/assets/icons/linux/linux-original.svg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'livewire',
                'slug' => Str::slug('livewire'),
                'type' => TypeTechnology::type_frontend,
                'icon' => '/assets/icons/livewire/livewire-original.svg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'mariadb',
                'slug' => Str::slug('mariadb'),
                'type' => TypeTechnology::type_backend,
                'icon' => '/assets/icons/mariadb/mariadb-original.svg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'markdown',
                'slug' => Str::slug('markdown'),
                'type' => TypeTechnology::type_devops,
                'icon' => '/assets/icons/markdown/markdown-original-negative.svg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'maven',
                'slug' => Str::slug('maven'),
                'type' => TypeTechnology::type_devops,
                'icon' => '/assets/icons/maven/maven-original.svg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'microsoftsqlserver',
                'slug' => Str::slug('microsoftsqlserver'),
                'type' => TypeTechnology::type_backend,
                'icon' => '/assets/icons/microsoftsqlserver/microsoftsqlserver-original.svg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'mongodb',
                'slug' => Str::slug('mongodb'),
                'type' => TypeTechnology::type_backend,
                'icon' => '/assets/icons/mongodb/mongodb-original.svg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'mysql',
                'slug' => Str::slug('mysql'),
                'type' => TypeTechnology::type_backend,
                'icon' => '/assets/icons/mysql/mysql-original.svg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'nextjs',
                'slug' => Str::slug('nextjs'),
                'type' => TypeTechnology::type_frontend,
                'icon' => '/assets/icons/nextjs/nextjs-original.svg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'nginx',
                'slug' => Str::slug('nginx'),
                'type' => TypeTechnology::type_devops,
                'icon' => '/assets/icons/nginx/nginx-original.svg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'nodejs',
                'slug' => Str::slug('nodejs'),
                'type' => TypeTechnology::type_backend,
                'icon' => '/assets/icons/nodejs/nodejs-original.svg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'npm',
                'slug' => Str::slug('npm'),
                'type' => TypeTechnology::type_devops,
                'icon' => '/assets/icons/npm/npm-original-wordmark.svg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'nuget',
                'slug' => Str::slug('nuget'),
                'type' => TypeTechnology::type_devops,
                'icon' => '/assets/icons/nuget/nuget-original.svg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'numpy',
                'slug' => Str::slug('numpy'),
                'type' => TypeTechnology::type_backend,
                'icon' => '/assets/icons/numpy/numpy-original.svg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'nuxtjs',
                'slug' => Str::slug('nuxtjs'),
                'type' => TypeTechnology::type_frontend,
                'icon' => '/assets/icons/nuxtjs/nuxtjs-original.svg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'oracle',
                'slug' => Str::slug('oracle'),
                'type' => TypeTechnology::type_backend,
                'icon' => '/assets/icons/oracle/oracle-original.svg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'php',
                'slug' => Str::slug('php'),
                'type' => TypeTechnology::type_backend,
                'icon' => '/assets/icons/php/php-original.svg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'postman',
                'slug' => Str::slug('postman'),
                'type' => TypeTechnology::type_devops,
                'icon' => '/assets/icons/postman/postman-original.svg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'python',
                'slug' => Str::slug('python'),
                'type' => TypeTechnology::type_backend,
                'icon' => '/assets/icons/python/python-original.svg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'react',
                'slug' => Str::slug('react'),
                'type' => TypeTechnology::type_frontend,
                'icon' => '/assets/icons/react/react-original.svg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'redis',
                'slug' => Str::slug('redis'),
                'type' => TypeTechnology::type_backend,
                'icon' => '/assets/icons/redis/redis-original.svg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sass',
                'slug' => Str::slug('sass'),
                'type' => TypeTechnology::type_frontend,
                'icon' => '/assets/icons/sass/sass-original.svg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'spring',
                'slug' => Str::slug('spring'),
                'type' => TypeTechnology::type_backend,
                'icon' => '/assets/icons/spring/spring-original.svg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sqlite',
                'slug' => Str::slug('sqlite'),
                'type' => TypeTechnology::type_backend,
                'icon' => '/assets/icons/sqlite/sqlite-original.svg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ssh',
                'slug' => Str::slug('ssh'),
                'type' => TypeTechnology::type_devops,
                'icon' => '/assets/icons/ssh/ssh-original.svg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'typescript',
                'slug' => Str::slug('typescript'),
                'type' => TypeTechnology::type_frontend,
                'icon' => '/assets/icons/typescript/typescript-original.svg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'tailwindcss',
                'slug' => Str::slug('tailwindcss'),
                'type' => TypeTechnology::type_frontend,
                'icon' => '/assets/icons/tailwindcss/tailwindcss-original.svg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ubuntu',
                'slug' => Str::slug('ubuntu'),
                'type' => TypeTechnology::type_devops,
                'icon' => '/assets/icons/ubuntu/ubuntu-original.svg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'vercel',
                'slug' => Str::slug('vercel'),
                'type' => TypeTechnology::type_devops,
                'icon' => '/assets/icons/vercel/vercel-original-negative.svg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'vitejs',
                'slug' => Str::slug('vitejs'),
                'type' => TypeTechnology::type_devops,
                'icon' => '/assets/icons/vitejs/vitejs-original.svg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
