<?php

namespace Database\Seeders;

use App\Enums\TypeTechnology;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class TechnologySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('technologies')->insert([
                [
                    'name' => 'Alpine JS',
                    'slug' => Str::slug('alpine js'),
                    'type' => TypeTechnology::type_frontend,
                    'icon' => '/assets/icons/alpinejs/alpinejs-original.svg',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Amazon Web Services',
                    'slug' => Str::slug('amazon web services'),
                    'type' => TypeTechnology::type_cloud,
                    'icon' => '/assets/icons/amazonwebservices/amazonwebservices-original-wordmark.svg',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Apache',
                    'slug' => Str::slug('apache'),
                    'type' => TypeTechnology::type_backend,
                    'icon' => '/assets/icons/apache/apache-original.svg',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Axios',
                    'slug' => Str::slug('axios'),
                    'type' => TypeTechnology::type_frontend,
                    'icon' => '/assets/icons/axios/axios-plain.svg',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Azure DevOps',
                    'slug' => Str::slug('azure devops'),
                    'type' => TypeTechnology::type_devops,
                    'icon' => '/assets/icons/azuredevops/azuredevops-original.svg',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Bash',
                    'slug' => Str::slug('bash'),
                    'type' => TypeTechnology::type_devops,
                    'icon' => '/assets/icons/bash/bash-original.svg',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Bootstrap',
                    'slug' => Str::slug('bootstrap'),
                    'type' => TypeTechnology::type_frontend,
                    'icon' => '/assets/icons/bootstrap/bootstrap-original.svg',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Cloudflare',
                    'slug' => Str::slug('cloudflare'),
                    'type' => TypeTechnology::type_cloud,
                    'icon' => '/assets/icons/cloudflare/cloudflare-original.svg',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Composer',
                    'slug' => Str::slug('composer'),
                    'type' => TypeTechnology::type_backend,
                    'icon' => '/assets/icons/composer/composer-original.svg',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'C#',
                    'slug' => Str::slug('c#'),
                    'type' => TypeTechnology::type_backend,
                    'icon' => '/assets/icons/csharp/csharp-original.svg',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'CSS3',
                    'slug' => Str::slug('css3'),
                    'type' => TypeTechnology::type_frontend,
                    'icon' => '/assets/icons/css3/css3-original.svg',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Digital Ocean',
                    'slug' => Str::slug('digital ocean'),
                    'type' => TypeTechnology::type_cloud,
                    'icon' => '/assets/icons/digitalocean/digitalocean-original.svg',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Docker',
                    'slug' => Str::slug('docker'),
                    'type' => TypeTechnology::type_devops,
                    'icon' => '/assets/icons/docker/docker-original.svg',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'GitHub',
                    'slug' => Str::slug('github'),
                    'type' => TypeTechnology::type_devops,
                    'icon' => '/assets/icons/github/github-original-negative.svg',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'HTML5',
                    'slug' => Str::slug('html5'),
                    'type' => TypeTechnology::type_frontend,
                    'icon' => '/assets/icons/html5/html5-original.svg',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Java',
                    'slug' => Str::slug('java'),
                    'type' => TypeTechnology::type_backend,
                    'icon' => '/assets/icons/java/java-original.svg',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'JavaScript',
                    'slug' => Str::slug('javascript'),
                    'type' => TypeTechnology::type_frontend,
                    'icon' => '/assets/icons/javascript/javascript-original.svg',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'jQuery',
                    'slug' => Str::slug('jquery'),
                    'type' => TypeTechnology::type_frontend,
                    'icon' => '/assets/icons/jquery/jquery-original.svg',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Laravel',
                    'slug' => Str::slug('laravel'),
                    'type' => TypeTechnology::type_backend,
                    'icon' => '/assets/icons/laravel/laravel-original.svg',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Linux',
                    'slug' => Str::slug('linux'),
                    'type' => TypeTechnology::type_devops,
                    'icon' => '/assets/icons/linux/linux-original.svg',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Livewire',
                    'slug' => Str::slug('livewire'),
                    'type' => TypeTechnology::type_frontend,
                    'icon' => '/assets/icons/livewire/livewire-original.svg',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'MariaDB',
                    'slug' => Str::slug('mariadb'),
                    'type' => TypeTechnology::type_database,
                    'icon' => '/assets/icons/mariadb/mariadb-original.svg',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Markdown',
                    'slug' => Str::slug('markdown'),
                    'type' => TypeTechnology::type_devops,
                    'icon' => '/assets/icons/markdown/markdown-original-negative.svg',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Maven',
                    'slug' => Str::slug('maven'),
                    'type' => TypeTechnology::type_devops,
                    'icon' => '/assets/icons/maven/maven-original.svg',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Microsoft SQL Server',
                    'slug' => Str::slug('microsoft sql server'),
                    'type' => TypeTechnology::type_database,
                    'icon' => '/assets/icons/microsoftsqlserver/microsoftsqlserver-original.svg',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'MongoDB',
                    'slug' => Str::slug('mongodb'),
                    'type' => TypeTechnology::type_database,
                    'icon' => '/assets/icons/mongodb/mongodb-original.svg',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'MySQL',
                    'slug' => Str::slug('mysql'),
                    'type' => TypeTechnology::type_database,
                    'icon' => '/assets/icons/mysql/mysql-original.svg',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Next.js',
                    'slug' => Str::slug('next.js'),
                    'type' => TypeTechnology::type_frontend,
                    'icon' => '/assets/icons/nextjs/nextjs-original.svg',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Nginx',
                    'slug' => Str::slug('nginx'),
                    'type' => TypeTechnology::type_devops,
                    'icon' => '/assets/icons/nginx/nginx-original.svg',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Node.js',
                    'slug' => Str::slug('node.js'),
                    'type' => TypeTechnology::type_backend,
                    'icon' => '/assets/icons/nodejs/nodejs-original.svg',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'PHP',
                    'slug' => Str::slug('php'),
                    'type' => TypeTechnology::type_backend,
                    'icon' => '/assets/icons/php/php-original.svg',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Python',
                    'slug' => Str::slug('python'),
                    'type' => TypeTechnology::type_backend,
                    'icon' => '/assets/icons/python/python-original.svg',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'React',
                    'slug' => Str::slug('react'),
                    'type' => TypeTechnology::type_frontend,
                    'icon' => '/assets/icons/react/react-original.svg',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Sass',
                    'slug' => Str::slug('sass'),
                    'type' => TypeTechnology::type_frontend,
                    'icon' => '/assets/icons/sass/sass-original.svg',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'TypeScript',
                    'slug' => Str::slug('typescript'),
                    'type' => TypeTechnology::type_frontend,
                    'icon' => '/assets/icons/typescript/typescript-original.svg',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Vue.js',
                    'slug' => Str::slug('vue.js'),
                    'type' => TypeTechnology::type_frontend,
                    'icon' => '/assets/icons/vuejs/vuejs-original.svg',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]
        );
    }
}
