services:
    production:
        container_name: portfolio
        image: portfolio
        environment:
            APP_ENV: production
        secrets:
            - production_key
            - production_env
        ports:
            - "8000:80"
secrets:
    production_env:
        file: /etc/secrets/portfolio/production/.env.production.encrypted
    production_key:
        file: /etc/secrets/portfolio/production/.env.production.key